### ISSUE TITLE
Bug: Character going out of frame

### ISSUE THREAD

**Issue by umgustavo** [naomiEve/VTubeTiny#2]
When I add the SimpleCharacterAnimator component, every time I speak the character jumps then goes down a little. In a reasonable amount of time, the character goes out of frame.

https://user-images.githubusercontent.com/19615514/207982007-d868f7d4-d939-4f16-ae8e-7c01940b2809.mp4

**Comment by naomiEve** [comment]
fixed in 581c9bd1c9ce62d9c5a5d5a7cc872d7f3f39eb2e :) thank you for the report!
